import {
  mdiCogOutline,
  mdiLogout,
  mdiChevronDoubleLeft,
  mdiChevronDoubleRight,
  mdiLoading,
  mdiTrashCanOutline,
  mdiTrophyOutline,
  mdiAlertCircle,
  mdiStop,
  mdiCursorDefaultClick,
  mdiClipboardOutline,
  mdiChevronRight,
  mdiClose,
  mdiHistory,
  mdiAccountOutline,
  mdiArchiveOutline,
  mdiClipboardListOutline,
  mdiCommentOutline,
  mdiViewDashboardOutline,
} from "@mdi/js";

export const MDI_ICONS = {
  loading: mdiLoading,
  history: mdiHistory,
  cog: mdiCogOutline,
  logout: mdiLogout,
  chevronDoubleLeft: mdiChevronDoubleLeft,
  chevronDoubleRight: mdiChevronDoubleRight,
  trash: mdiTrashCanOutline,
  trophy: mdiTrophyOutline,
  alert: mdiAlertCircle,
  stop: mdiStop,
  cursorDefault: mdiCursorDefaultClick,
  clipboard: mdiClipboardOutline,
  close: mdiClose,
  chevronRight: mdiChevronRight,
  account: mdiAccountOutline,
  archive: mdiArchiveOutline,
  clipboardList: mdiClipboardListOutline,
  comment: mdiCommentOutline,
  viewDashboard: mdiViewDashboardOutline,
};
