export const IconifyIcons = {
  loading: 'mdi:loading',
  history: 'mdi:history',
  cog: 'mdi:cog-outline',
  logout: 'mdi:logout',
  chevronDoubleLeft: 'mdi:chevron-double-left',
  chevronDoubleRight: 'mdi:chevron-double-right',
  trash: 'mdi:trash-can-outline',
  trophy: 'mdi:trophy-outline',
  alert: 'mdi:alert-circle',
  stop: 'mdi:stop',
  cursorDefault: 'mdi:cursor-default-click',
  clipboard: 'mdi:clipboard-outline',
  close: 'mdi:close',
  chevronRight: 'mdi:chevron-right',
  account: 'mdi:account-outline',
  archive: 'mdi:archive-outline',
  clipboardList: 'mdi:clipboard-list-outline',
  comment: 'mdi:comment-outline',
  viewDashboard: 'mdi:view-dashboard-outline',
  inProgress: 'mdi:hourglass',
};
